### ISSUE TITLE
iteratoraggregate not found

### ISSUE THREAD

**Issue by vcakmak** [bcosca/fatfree#774]
hello,

i get an error :(

Fatal error: Interface 'IteratorAggregate' not found
• test/lib/db/cursor.php:20 

i'm use

-php 5.4 (with spl)
-apache 2.4

**Comment by xfra35** [comment]
Are you Turkish? Because if yes, there's [again](https://github.com/bcosca/fatfree/issues/772) that "i" letter messing things up.

See:
```php
setlocale(LC_ALL,'en_US.UTF-8');
echo interface_exists('IteratorAggregate')?1:0;// outputs 1
setlocale(LC_ALL,'tr_TR.UTF-8');
echo interface_exists('IteratorAggregate')?1:0;// outputs 0
echo interface_exists('iteratorAggregate')?1:0;// outputs 1
```

I found these bugs on php.net:
* https://bugs.php.net/bug.php?id=35050
* https://bugs.php.net/bug.php?id=18556

From the last issue I understand that your issue may have been fixed in PHP 5.5:
> The bugs has only been fixed in 5.5 branch. It mainly uses a char map to lower 
characters instead of relying on locale-aware (possibly buggy versions) system's 
libc.

**Comment by KOTRET** [comment]
damn, shame on the php maintainers... -.-' such an old bug and still present in commonly used php versions

**Comment by bcosca** [comment]
As far as the framework is concerned, there's nothing to fix. It's an upstream bug.
